name: Publish to PyPI (Trusted Publishing)

on:
  release:
    types: [published]  
jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      contents: read    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"  

      - name: Install build tool
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
